<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Machine Learning - 2301CS621</b></center>

<center><b><h1>Lab - 1</b></center>    
<pre>    

# NumPy Exercises
## We'll start off with a few simple tasks

## import numpy as np

### What is NumPy? (5 Key Points)

1. **Core Purpose**: NumPy (Numerical Python) is the foundational library for numerical and scientific computing in Python.
2. **N-Dimensional Arrays (`ndarray`)**: Its central feature is the powerful, highly efficient multidimensional array object. Unlike standard Python lists, these arrays hold items of the same type and allow for fast, vectorized mathematical operations.
3. **High Performance**: Because its core operations are implemented in C, NumPy is incredibly fast. It executes complex computations on large datasets much more efficiently than standard Python loops and lists.
4. **Rich Mathematical Toolkit**: It provides a vast collection of built-in mathematical, logical, shape manipulation, sorting, and basic statistical operations that can be applied to entire arrays without needing explicit loops.
5. **Foundation of the Ecosystem**: NumPy serves as the bedrock for almost the entire Python data science and machine learning ecosystem. Popular libraries like Pandas, SciPy, scikit-learn, and TensorFlow are built on top of it or rely heavily on its array structures.


In [14]:
import numpy as np

In [2]:
n = np.array([1,2,3,4],dtype=str)

In [3]:
type(n)

numpy.ndarray

In [4]:
n

array(['1', '2', '3', '4'], dtype='<U1')

In [5]:
n.dtype

dtype('<U1')

## Create an array of 10 zeros

In [6]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Create an array of 10 ones

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Create an array of 10 fives

In [8]:
np.ones(10) *5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## Create an array of the integers from 10 to 50

In [9]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

## Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
np.arange(0,9,1).reshape(1,9)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

## Create a 3x3 identity matrix

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Create following matrix  = <br/>
<pre>array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])</pre>

In [12]:
n =np.arange(1,26,1).reshape(5,5)

## Output should be =
<pre>array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])</pre>

In [13]:
n[2::,1::]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

## Output should be = <br/>
<pre>array([[ 2],
       [ 7],
       [12]])</pre>

In [14]:
n[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

## Find Odd Numbers
Extract all odd numbers from `arr`.

`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])` <BR>
Use Condtional Selection

In [4]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = arr[arr % 2 == 1]
print(odd_numbers)

[1 3 5 7 9]


## Stacking
Stack array `a` and `b` vertically.

`a = np.arange(10).reshape(2,-1)`
`b = np.repeat(1, 10).reshape(2,-1)`

In [11]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
output = np.vstack([a, b])
print(output)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


##  Range Filtering
Get all items between 5 and 10 from `a`.

`a = np.array([2, 6, 1, 9, 10, 3, 27])`

In [9]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
output = a[(a >= 5) & (a <= 10)]
print(output)

[ 6  9 10]


## Matrix Multiplication
Multiply a 5x3 matrix by a 3x2 matrix (dot product).

In [10]:
A = np.random.random((5,3))
B = np.random.random((3,2))
product = np.dot(A, B)
print(product)

[[1.44576481 1.53425016]
 [1.09322182 0.67844804]
 [0.91008796 1.21252048]
 [0.89292414 0.60539749]
 [0.57727794 0.93558888]]


# Great Job! You’re Halfway Through 🚀  | PANDAS  Exercises



### Step 1. Import the necessary libraries

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user). 

### Step 3. Assign it to a variable called users and use the 'user_id' as index

### Step 4. See the first 25 entries

,age,gender,occupation,zip_code
user_id,,,,
1,24,M,technician,85711
2,53,F,other,94043
3,23,M,writer,32067
4,24,M,technician,43537
5,33,F,other,15213
6,42,M,executive,98101
7,57,M,administrator,91344
8,36,M,administrator,05201
9,29,M,student,01002


### Step 5. See the last 10 entries

,age,gender,occupation,zip_code
user_id,,,,
934,61,M,engineer,22902
935,42,M,doctor,66221
936,24,M,other,32789
937,48,M,educator,98072
938,38,F,technician,55038
939,26,F,student,33319
940,32,M,administrator,02215
941,20,M,student,97229
942,48,F,librarian,78209


### Step 6. What is the number of observations in the dataset?

943

### Step 7. What is the number of columns in the dataset?

4

### Step 8. Print the name of all the columns.

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed?

In [ ]:
# "the index" (aka "the labels")


Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
            ...
            934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
           dtype='int64', name='user_id', length=943)

### Step 10. What is the data type of each column?

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

### Step 11. Print only the occupation column

user_id
1         technician
2              other
3             writer
4         technician
5              other
6          executive
7      administrator
8      administrator
9            student
10            lawyer
11             other
12             other
13          educator
14         scientist
15          educator
16     entertainment
17        programmer
18             other
19         librarian
20         homemaker
21            writer
22            writer
23            artist
24            artist
25          engineer
26          engineer
27         librarian
28            writer
29        programmer
30           student
           ...      
914            other
915    entertainment
916         engineer
917          student
918        scientist
919            other
920           artist
921          student
922    administrator
923          student
924            other
925         salesman
926    entertainment
927       programmer
928          student
929        scientist
930  

### Step 12. How many different occupations are in this dataset?

21

### Step 13. What is the most frequent occupation?

'student'

### Step 14. Summarize the DataFrame.

,age
count,943.000000
mean,34.051962
std,12.192740
min,7.000000
25%,25.000000
50%,31.000000
75%,43.000000
max,73.000000


### Step 15. Summarize all the columns

,age,gender,occupation,zip_code
count,943.000000,943,943,943
unique,NaN,2,21,795
top,NaN,M,student,55414
freq,NaN,670,196,9
mean,34.051962,NaN,NaN,NaN
std,12.192740,NaN,NaN,NaN
min,7.000000,NaN,NaN,NaN
25%,25.000000,NaN,NaN,NaN
50%,31.000000,NaN,NaN,NaN
75%,43.000000,NaN,NaN,NaN


### Step 16. Summarize only the occupation column

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

34

### Step 18. What is the age with least occurrence?

11    1
10    1
73    1
66    1
7     1
Name: age, dtype: int64